{
 "title": "RabbitMQ / Queue",
 "description": "A dashboard that monitors RabbitMQ. It is created using the (rabbitmq-mixin)[https://github.com/adinhodovic/rabbitmq-mixin].",
 "tags": [
  "rabbitmq",
  "rabbitmq-mixin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(rabbitmq_identity_info, namespace)"
   },
   {
    "name": "rabbitmq_cluster",
    "label": "Cluster",
    "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\"}, rabbitmq_cluster)"
   },
   {
    "name": "vhost",
    "label": "Virtual Host",
    "query": "label_values(rabbitmq_queue_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}, vhost)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(rabbitmq_queue_info{vhost=~\"$vhost\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_detailed_queue_consumers{vhost=~\"$vhost\"}\n* on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"})\n"
    }
   ]
  },
  {
   "title": "Queues with Messages Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_detailed_queue_messages_ready{vhost=~\"$vhost\"}\n* on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"} > 0)\n"
    }
   ]
  },
  {
   "title": "Queues with Messages Unacked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_detailed_queue_messages_unacked{vhost=~\"$vhost\"}\n* on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"} > 0)\n"
    }
   ]
  },
  {
   "title": "Virtual Host Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Host Ready & Unacked Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_ready{namespace=\"$namespace\", vhost=~\"$vhost\"}[$__rate_interval]\n  )\n) by (instance, vhost)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Ready - {{ vhost }}"
    },
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_unacked{namespace=\"$namespace\", vhost=~\"$vhost\"}[$__rate_interval]\n  )\n) by (instance, vhost)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Unacked - {{ vhost }}"
    }
   ]
  },
  {
   "title": "Queue Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Length & Consumers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (instance, vhost, queue) (rabbitmq_detailed_queue_consumers{vhost=~\"$vhost\", namespace=\"$namespace\", queue=~\"$queue\"})\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n"
    },
    {
     "expr": "sum by (instance, vhost, queue) (rabbitmq_detailed_queue_messages{vhost=~\"$vhost\", namespace=\"$namespace\", queue=~\"$queue\"})\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n"
    }
   ]
  },
  {
   "title": "Queue Ready & Unacked Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_ready{namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__rate_interval]\n  )\n) by (instance, vhost, queue)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Ready - {{ queue }}/{{ vhost }}"
    },
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_unacked{namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__rate_interval]\n  )\n) by (instance, vhost, queue)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Unacked - {{ queue }}/{{ vhost }}"
    }
   ]
  }
 ]
}