global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
    metrics_path: "/metrics"
    scheme: http
    basic_auth:
      username: ${RABBITMQ_USER:-rabbitmq}
      password: ${RABBITMQ_PASS:-rabbitmq}
