version: "3.7"

volumes:
  redis_cache:
    driver: local

services:

  redis:
    image: redis
    container_name: crvrs-media-redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ${REDIS_CACHE_DIR:-redis_cache}:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
  